[package]
name = "wallpaper"
version = "0.1.0"
edition = "2021"

[dependencies]
wallpaper = { version = "3.2.0", features = ["from_url"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"


[[bin]]
edition = "2018"
name = "changewpp"
path = "src/main.rs"
